name: bitsquare
version: "master"
summary: Peer-to-peer exchange to trade various curriencies for bitcoin
description: |
  Cross-platform desktop application that allows users to trade national currency (dollars, euros, etc) for bitcoin without relying on centralized exchanges
confinement: devmode

apps:
  bitsquare:
    command: usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dsecurity.provider.11=org.bouncycastle.jce.provider.BouncyCastleProvider -jar $SNAP/gui/shaded.jar "$@"
    plugs: [home, network, network-bind]

parts:
  bitsquare:
    plugin: maven
    maven-targets:
      - gui
    maven-options:
      - -DskipTests
      - -Dmaven.javadoc.skip=true
    source: https://github.com/bitsquare/bitsquare.git
    build-packages: [openjfx]
    stage-packages: [openjfx]
    after: [bitcoinj]

  bitcoinj:
    plugin: maven
    maven-targets:
      - core
    maven-options:
      - -DskipTests
      - -Dmaven.javadoc.skip=true
    source: https://github.com/bitsquare/bitcoinj.git
    source-branch: FixBloomFilters
    build-packages: [openjfx]
    stage-packages: [openjfx]
        
# vim:tabstop=2 shiftwidth=2 expandtab
