name: bitsquare
version: "master"
summary: Peer-to-peer exchange to trade various curriencies for bitcoin
description: |
  Cross-platform desktop application that allows users to trade national currency (dollars, euros, etc) for bitcoin without relying on centralized exchanges
confinement: devmode

apps:
  bitsquare:
    command: bin/wrapper.bash
    plugs: [home, network, network-bind, x11]

parts:
  bitsquare:
    plugin: maven
    maven-targets:
      - gui
    maven-options:
      - -DskipTests
      - -Dmaven.javadoc.skip=true
    source: https://github.com/bitsquare/bitsquare.git
    build-packages: [openjfx]
    stage-packages: [openjfx]
    after: [bitcoinj]

  bitcoinj:
    plugin: maven
    maven-targets:
      - core
    maven-options:
      - install
      - -DskipTests
      - -Dmaven.javadoc.skip=true
    source: https://github.com/bitsquare/bitcoinj.git
    source-branch: FixBloomFilters
    build-packages: [openjfx]
    stage-packages: [openjfx]

  # It will copy wrapper.bash script into /bin/
  # This script contains all the commands needed (sets env variables, launches the jar file...) to
  # execute the application
  exec:
    plugin: dump
    source: .
    organize:
      wrapper.bash: bin/wrapper.bash
        
# vim:tabstop=2 shiftwidth=2 expandtab
