name: bisq-desktop
version: "master"
summary: Peer-to-peer exchange to trade various curriencies for bitcoin
description: |
  Cross-platform desktop application that allows users to trade national currency (dollars, euros, etc) for bitcoin without relying on centralized exchanges
confinement: strict
grade: stable

apps:
  bisq-desktop:
    command: desktop-launch "$SNAP/opt/bisq/bin/bisq-desktop"
    plugs: [home, network, network-bind, x11]

parts:
  bisq:
    plugin: gradle
    override-build: |
      ./gradlew build

      # Install executable.
      install -d "${SNAPCRAFT_PART_INSTALL}/opt/bisq"
      cp -r build/app/* "${SNAPCRAFT_PART_INSTALL}/opt/bisq"

      # Install desktop launcher icon
      install -Dm644 package/linux/icon.png "${SNAPCRAFT_PART_INSTALL}/usr/share/pixmaps/bisq.png"

    source: https://github.com/bisq-network/bisq-desktop.git
    source-tag: v0.8.0
    build-packages: [openjfx]
    stage-packages: [openjfx]
    after: [desktop-gtk3]

  # Install desktop launcher
  desktop-file:
    plugin: dump
    source: .
    organize:
      'desktop.bisq': usr/share/applications/bisq.desktop
    after:
      - bisq
        
# vim:tabstop=2 shiftwidth=2 expandtab
