name: bisq-desktop
base: core18
version: 1.2.9
summary: Peer-to-peer exchange to trade various curriencies for bitcoin
description: |
  Cross-platform desktop application that allows users to trade national currency (dollars, euros, etc) for bitcoin without relying on centralized exchanges
confinement: strict
grade: stable
icon: icon.png

apps:
  bisq-desktop:
    extensions:
      - gnome-3-28
    command: opt/Bisq/Bisq
    plugs:
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - home
      - gsettings
      - camera
      - opengl
    desktop: usr/share/applications/bisq.desktop
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"

parts:
  bisq:
    plugin: dump
    source: https://github.com/bisq-network/bisq/releases/download/v1.2.9/Bisq-64bit-1.2.9.deb
    source-checksum: sha256/eccc96101931cb88b38e40a73137a46275bbb176732c54c3bdef2370b18949de
    stage-packages:
      - libgl1
      - libglx0
      - libxtst6
      - libxxf86vm1
      - libv4l-0
      - libasound2
      - freeglut3
      - libgtk2.0-0
      - libavcodec57
      - libavformat57

  # Install desktop launcher
  launchers:
    plugin: dump
    source: .
    organize:
      'bisq.desktop': usr/share/applications/bisq.desktop
    after:
      - bisq

# vim:tabstop=2 shiftwidth=2 expandtab
